<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>


    <IsPackable>true</IsPackable>
    <IsTestProject>false</IsTestProject>
    <PackageId>NatLaOpcUaTest.Services</PackageId>
    <Description>Implemented services used by NatLaOpcUaTest Gherkin bindings.</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.1" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.5.378.156" />
    <PackageReference Include="Reqnroll" Version="3.3.2" />
    <PackageReference Include="Rotbarsch.Reqnroll.Services" Version="0.26.725" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NatLaOpcUaTest.Services.Interfaces\NatLaOpcUaTest.Services.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
